# Welcome to the ${project.name} configuration file!

Experience Bar:
    Format: '@skill (Level @level)'
    # Seconds until disappear
    disappear: 15
    # Colorize the skill name
    Color:
        MINING: '3'
        WOODCUTTING: 'a'
        HERBALISM: '2'
        EXCAVATION: '6'
        FISHING: '1'
        UNARMED: 'd'
        SWORDS: 'c'
        TAMING: 'f'
        ARCHERY: '5'
        AXES: '4'
        REPAIR: 'd'
        ACROBATICS: 'c'
        SMELTING: '7'
        ALCHEMY: '9'

# Should the plugin automatically download a update from the project if it's available
autoUpdate: true