# Welcome to the ${project.name} configuration file!

bar:
    format: '@skill (Level @level)'
    # Seconds until disappear
    disappear: 15
    # Colorize the skill name
    color:
        mining: '3'
        woodcutting: 'a'
        herbalism: '2'
        excavation: '6'
        fishing: '1'
        unarmed: 'd'
        swords: 'c'
        taming: 'f'
        archery: '5'
        axes: '4'
        repair: 'd'
        acrobatics: 'c'
        smelting: '7'
        alchemy: '9'
    # 1.9+ only settings
    # If the value is empty it will be ignored
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
    barColor:
        mining: 'GREEN '
        woodcutting: 'GREEN'
        herbalism: 'GREEN'
        excavation: 'GREEN'
        fishing: 'GREEN'
        unarmed: 'GREEN'
        swords: 'GREEN'
        taming: 'GREEN'
        archery: 'GREEN'
        axes: 'GREEN'
        repair: 'GREEN'
        acrobatics: 'GREEN'
        smelting: 'GREEN'
        alchemy: 'GREEN'
    # 1.9+ only settings
    # If the value is empty it will be ignored
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
    segments:
        mining: 'SOLID'
        woodcutting: 'SOLID'
        herbalism: 'SOLID'
        excavation: 'SOLID'
        fishing: 'SOLID'
        unarmed: 'SOLID'
        swords: 'SOLID'
        taming: 'SOLID'
        archery: 'SOLID'
        axes: 'SOLID'
        repair: 'SOLID'
        acrobatics: 'SOLID'
        smelting: 'SOLID'
        alchemy: 'SOLID'

# Should the bar always show up
alwaysShow: false

# Checks the region the player is in and shows only if the skill is listed in a flag there
useWorldGuardFlags: false

# permission based max levels
permissions:
    # permission group
    guest:
        # skill type: max level to show the level in the bar
        unarmed: 100

# 1.9+ only settings
# This is value is used if no specific segments style is set (See above)
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
segments: SOLID

## This is value is used if no specific color is set (See above)
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
color: PURPLE

# How many bars should be displayed at the same time
concurrentBars: 2
